const prefix = 'style.';

let stylePropsList = undefined;

const names = [
    'alignContent',
    'alignItems',
    'background',
    'backgroundAttachment',
    'backgroundColor',
    'backgroundImage',
    'backgroundPosition',
    'backgroundRepeat',
    'border',
    'borderBottom',
    'borderBottomColor',
    'borderBottomStyle',
    'borderBottomWidth',
    'borderColor',
    'borderLeft',
    'borderLeftColor',
    'borderLeftStyle',
    'borderLeftWidth',
    'borderRadius',
    'borderRight',
    'borderRightColor',
    'borderRightStyle',
    'borderRightWidth',
    'borderStyle',
    'borderTop',
    'borderTopColor',
    'borderTopStyle',
    'borderTopWidth',
    'borderWidth',
    'bottom',
    'clear',
    'clip',
    'color',
    'cursor',
    'display',
    'filter',
    'flexDirection',
    'flexFlow',
    'flexWrap',
    'font',
    'fontFamily',
    'fontSize',
    'fontVariant',
    'fontWeight',
    'height',
    'justifyContent',
    'left',
    'letterSpacing',
    'lineHeight',
    'listStyle',
    'listStyleImage',
    'listStylePosition',
    'listStyleType',
    'margin',
    'marginBottom',
    'marginLeft',
    'marginRight',
    'marginTop',
    'maxHeight',
    'maxWidth',
    'minHeight',
    'minWidth',
    'overflow',
    'right',
    'padding',
    'paddingBottom',
    'paddingLeft',
    'paddingRight',
    'paddingTop',
    'pageBreakAfter',
    'pageBreakBefore',
    'position',
    'cssFloat',
    'textAlign',
    'textDecoration',
    'textDecorationBlink',
    'textDecorationLineThrough',
    'textDecorationNone',
    'textDecorationOverline',
    'textDecorationUnderline',
    'textIndent',
    'textTransform',
    'top',
    'verticalAlign',
    'visibility',
    'width',
    'zIndex'
];

export function getStylePropList(){
    if(!stylePropsList){
        stylePropsList = [];
        names.forEach(name => {
            stylePropsList.push(prefix + name);
        });
    }
    return stylePropsList;
}
